-- 1.
SELECT 
  conta_numero,
  TO_CHAR(saldo, 'FM9G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS saldo_formatado
FROM conta;

-- 2.
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS data_atual FROM DUAL;

-- 3.
SELECT cliente_nome || ' - ' || cidade AS nome_com_cidade
FROM cliente;

-- 4.
SELECT 
  emprestimo_numero,
  'R$ ' || TO_CHAR(quantia, 'FM9G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS valor_formatado
FROM emprestimo
WHERE quantia > 5000;

-- 5.
ALTER TABLE cliente ADD (data_cadastro TIMESTAMP);

-- 6.
SELECT 
  cliente_cod,
  cliente_nome,
  data_cadastro,
  CASE 
    WHEN data_cadastro IS NULL THEN NULL
    ELSE TRUNC(SYSDATE) - TRUNC(data_cadastro)
  END AS dias_desde_cadastro
FROM cliente;

-- 7.
ALTER TABLE cliente ADD (tempo_fidelidade INTERVAL YEAR TO MONTH);

-- 8.
SELECT 
  cliente_cod,
  cliente_nome,
  data_cadastro,
  (data_cadastro + INTERVAL '3' MONTH) AS previsao_renovacao
FROM cliente;

-- 9.
CREATE TABLE cartao_credito (
  cartao_numero   VARCHAR2(20) NOT NULL,
  cliente_cod     INTEGER NOT NULL,
  limite_credito  NUMBER(12,2) NOT NULL,
  status          VARCHAR2(10) NOT NULL,
  CONSTRAINT cartao_pk PRIMARY KEY (cartao_numero),
  CONSTRAINT cartao_cliente_fk FOREIGN KEY (cliente_cod) REFERENCES cliente(cliente_cod),
  CONSTRAINT cartao_status_ck CHECK (status IN ('ATIVO','BLOQUEADO','CANCELADO'))
);

-- 10.
INSERT INTO cartao_credito (cartao_numero, cliente_cod, limite_credito, status)
VALUES ('1111-2222-3333-4444', 1, NULL, 'ATIVO');

-- 11.
INSERT INTO cartao_credito (cartao_numero, cliente_cod, limite_credito, status)
VALUES ('4000-1234-0001-0001', 1, 5000.00, 'ATIVO');
INSERT INTO cartao_credito (cartao_numero, cliente_cod, limite_credito, status)
VALUES ('4000-1234-0002-0002', 2, 2500.00, 'BLOQUEADO');
INSERT INTO cartao_credito (cartao_numero, cliente_cod, limite_credito, status)
VALUES ('4000-1234-0003-0003', 3, 10000.00, 'ATIVO');

-- 12.
CREATE TABLE transacao (
  transacao_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  conta_numero    INTEGER NOT NULL,
  valor           NUMBER(12,2) NOT NULL,
  data_transacao  DATE DEFAULT SYSDATE,
  CONSTRAINT transacao_pk PRIMARY KEY (transacao_id),
  CONSTRAINT transacao_conta_fk FOREIGN KEY (conta_numero) REFERENCES conta(conta_numero),
  CONSTRAINT transacao_valor_ck CHECK (valor > 0)
);

-- 13.
INSERT INTO transacao (conta_numero, valor) VALUES (1, -150.00);

-- 14.
SELECT
  c.cliente_cod,
  c.cliente_nome,
  cc.cartao_numero,
  cc.limite_credito
FROM cliente c
JOIN cartao_credito cc ON c.cliente_cod = cc.cliente_cod
WHERE cc.status = 'ATIVO'
  AND cc.limite_credito > 3000;